# Generated by Django 4.2.7 on 2024-11-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('passout', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('college_name', models.CharField(max_length=255)),
                ('tech_field', models.CharField(max_length=255)),
                ('is_lead', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('follow_up', models.DateField(blank=True, null=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.status')),
            ],
        ),
    ]
